### ISSUE TITLE
Vicon Repository Broken?

### ISSUE THREAD

**Issue by formica-multiuso** [blandry/crazyflie-tools#20]
Hi blandry,
is your vicon repository broken?
It's linked to anything. :/

Let me know.
formica

**Comment by peteflorence** [comment]
Hi Formica,

The Vicon library contains proprietary software so is not open.

Maybe we can think of a different solution for you.

Best,

Pete

**Comment by blandry** [comment]
Yes like Pete said we would be happy to give you the client but there is a library in that repository that is proprietary to Vicon. It is their SDK (libViconDataStreamSDK_CPP.so). If you have that file through them we can just give you access to a copy of that folder without that file.

Cheers,
-Benoit

**Comment by formica-multiuso** [comment]
Thanks for the quick response.
I have not a Vicon systems, but an Optitrack system instead.
I was thinking to look at the vicon directory to learn how to adapt your project for an optitrack system.

Can you provide me some references, or infos that can help me?

Cheers,
-Roberto

**Comment by blandry** [comment]
The Vicon folder contains a client that listens to the vicon stream and publishes the position of the object being tracked using LCM. That's all it does. I will make a copy of the folder without the libraries so you can get an idea.

**Comment by blandry** [comment]
So I just double checked and the client example our client was based on is also copyrighted. But essentially if you get Optitrack to publish LCM messages of this type

package vicon_t;

    struct vicon_pos_t
    {
    	int64_t timestamp;
    	double q[6];
    }

then the rest of the software should work. Does optitrack provide some dev library of some sort?

**Comment by formica-multiuso** [comment]
Following your hints I wrote this:
https://github.com/formica-multiuso/OptitrackViconLcmStub

I have to test it deeply. I don't know, right now, if the quaternion->euler convertion is correct...
The overall infrastructure and communication is working.
Work in progress..

- roberto

**Comment by blandry** [comment]
This is awesome. Do you want us to link to your repo from crazyflie-tools? This way other people using Optitrack can find it right away. 

Also for the quaternion conversion here are some implementations to test against (unfortunately I don't think we have any in C++ right now):
MATLAB: https://github.com/RobotLocomotion/drake/blob/master/util/quat2rpy.m
Python: quat2rpy in https://github.com/blandry/crazyflie-tools/blob/master/estimation/transforms.py
C: sensfusion6GetEulerRPY in https://github.com/peteflorence/crazyflie-firmware-2/blob/crazyflie2-build/modules/src/sensfusion6.c

**Comment by formica-multiuso** [comment]
Of course you can. It's free software, free as in freedom. ;)

I will check the quaternions conversion asap.

Rob
