### ISSUE TITLE
crazyflie-client-python console: no CF2 bootstrap data

### ISSUE THREAD

**Issue by formica-multiuso** [blandry/crazyflie-tools#22]
Hi guys,
as you know I flashed the CF2 with your firmware.
I'm trying to obtain imu data... but it seems that the copter doesn't communicate properly with the copter.
Using the console of your modified python client I don't get any CF's bootstrap information (DEBUG_PRINT in system.c).
Otherwise, I can see correctly those infos in the console of a standard python client.

Any idea?

**Comment by joaoolavo** [comment]
@formica-multiuso Did you manage to get the angles from the IMU?
