### ISSUE TITLE
Question on estimation/models.py 

### ISSUE THREAD

**Issue by mjlakis** [blandry/crazyflie-tools#29]
I think the force of each motor proportional to the square speed of the motor? Similarly for the moment? (saying this after reading your thesis)
Would you please check lines 109 through 116 in estimation/models.py

Amazing work btw. Thanks for sharing.

**Comment by blandry** [comment]
You are correct regarding the model depending on the square of the prop angular velocity. If I remember well this code was due to the fact that wi was actually the squared angular velocity in our case. Basically a poor choice of variable name.

**Comment by mjlakis** [comment]
I see, thank you for clarifying.
